apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-resource-boundary.yaml
  - 02-serviceaccount.yaml
  - 03-externalsecret.yaml
  - 04-configmap.yaml
  - 05-deployment.yaml
  - 06-service.yaml
  - 07-networkpolicy-egress.yaml
